// src/components/footer/footer.tsx
import { component$ } from "@builder.io/qwik";

export default component$(() => {
  return (
    <footer>
      <div>
        <span>
          © 2023 High Performance Computing System Laboratory (HPCS Lab.),
          hpcs-web [at] hpcs.cs.tsukuba.ac.jp
        </span>
      </div>
    </footer>
  );
});

// src/lib/components/Footer.svelte
<footer id="colophon" class="site-footer" role="contentinfo">
	<div class="footer-main">
		<div class="container">
			<div class="clear"></div>
		</div>
	</div>
	<div class="bottom-bar">
		<div class="container">
			<div class="site-info">
				© 2023 High Performance Computing System Laboratory (HPCS Lab.), hpcs-web [at]
				hpcs.cs.tsukuba.ac.jp
			</div>
		</div>
	</div>
</footer>
